const configuredBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export function assetPath(path: string) {
  return `${configuredBasePath}${path}`;
}

// Generated by scripts/prepare-thumbnails.mjs for gallery source assets.
export function thumbnailPath(path: string) {
  return path.replace(/\.(?:webp|jpg)$/i, "-thumb.webp");
}
